/*********************************************************************/
/*                                                                   */
/*  STRBFCTOM   Start BFC Tomcat Server                              */
/*  20 August 2008                                                   */
/*  Max Blacknik                                                     */
/*                                                                   */
/*  Command Processing Program: STRBFCTOMC                           */
/*  Validity Checking Program:  None                                 */
/*                                                                   */
/*********************************************************************/
/*  Revisions:                                                       */
/*                                                                   */
/*                                                                   */
/*********************************************************************/
/*                                                                   */
/*  Parameters                                                       */
/*                                                                   */
/*       -None-                                                      */
/*                                                                   */
/*********************************************************************/

             CMD        PROMPT('Start BFC Tomcat Server')

